### ISSUE TITLE
Representation Collapse

### ISSUE THREAD

**Issue by arjung128** [lucidrains/byol-pytorch#12]
First of all, thank you so much for making this work open source!

My question isn't directly related to your implementation but rather a question about the paper -- I didn't know where else to ask, and I figured you'd have a pretty good understanding of the paper. Having said that, feel free to mark it closed if you think it is inappropriate.

I recently read the paper and I don't understand why the network doesn't cheat by simply learning to output 0s, or in their own words, by learning "collapsed representations." Any ideas?

**Comment by lucidrains** [comment]
@arjung128 The real answer is no one really knows for sure! But there's been some great discussion and theorizing why this works. https://www.reddit.com/r/MachineLearning/comments/hju274/d_byol_bootstrap_your_own_latent_cheating/ Read the first comment from programmerchilli

**Comment by arjung128** [comment]
Thanks a bunch for the references!
