### ISSUE TITLE
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

### ISSUE THREAD

**Issue by vumichien** [lucidrains/byol-pytorch#13]
I got this problem when I tried to call SelfSupervisedLearner like the example in Pytorch lightning. Do you have any suggestion for this

```
model = SelfSupervisedLearner(
        resnet,
        lr=LR,
        image_size = IMAGE_SIZE,
        hidden_layer = 'avgpool',
        projection_size = 256,
        projection_hidden_size = 4096,
        moving_average_decay = 0.99
    )
```

**Comment by zywbupt** [comment]
How did you solve this problem, I have met the same problem?

**Comment by vumichien** [comment]
You need to check the PyTorch lightnight version and install all the library requirements. Simply, this code works well when you run it on Colab
