### ISSUE TITLE
Pretrained network

### ISSUE THREAD

**Issue by pmorerio** [lucidrains/byol-pytorch#16]
Hi, thanks for sharing the code and making it so easy to use.
I see in the example you set `resnet = models.resnet50(pretrained=True)`.
Is this what is done in the paper? Shouldn't self-supervised-learned networks be trained from scratch?

Thanks again, 
P.

**Comment by lucidrains** [comment]
hello! this is what I was following

![Screenshot from 2020-07-13 12-36-38](https://user-images.githubusercontent.com/108653/87345856-8d0a6b00-c505-11ea-97bd-387d4bc525fc.png)

**Comment by pmorerio** [comment]
Thanks for the clarification!

**Comment by SDNAFIO** [comment]
Please be careful here.
This paragraph describes the Semi-Supervised experiments, not the linear evaluation on ImageNet.
Setting pretrained=True loads pretrained weights obtained by supervised(!) training on ImageNet.
This is definitely not what you want to do here.
