### ISSUE TITLE
Distributed training support

### ISSUE THREAD

**Issue by naveenkumarmarri** [lucidrains/byol-pytorch#2]
Is there any plan to support distributed training for the model?

**Comment by lucidrains** [comment]
@naveenkumarmarri Let me check if the test script works with Deepspeed later today

**Comment by lucidrains** [comment]
@naveenkumarmarri I just tested it with Deepspeed and it works well!

**Comment by naveenkumarmarri** [comment]
I tried with deepspeed, looks like it doesn't have option of using LARS scheduler with cosine annealing. Can you share minimal example of how to do this with deepspeed?
