### ISSUE TITLE
the error of the runing exampe code when i use 2 gpus

### ISSUE THREAD

**Issue by cuixianheng** [lucidrains/byol-pytorch#24]
Hi! When I try to run the Pytorch lightning example code. the training code is：
trainer = pl.Trainer(gpus=2, max_epochs=1000, distributed_backend='dp')，trainer.fit(model, train_loader)
I get the following error：
“AssertionError: hidden layer avgpool never emitted an output”
but when i use 1 gpu there is no error。can you give me some advice?

**Comment by lucidrains** [comment]
@cuixianheng Try 'ddp' instead of 'dp'. it should be the recommended default settings from now on!

**Comment by cuixianheng** [comment]
the problem is solved, thank you nver much!
