### ISSUE TITLE
the maximum batch size can only be set to 32

### ISSUE THREAD

**Issue by cuixianheng** [lucidrains/byol-pytorch#26]
When I run the code with a 2080ti GPU with 10G memory, the maximum batch size can only be set to 32. Is there any place in the code that takes up a lot of video memory?

**Comment by lucidrains** [comment]
@cuixianheng it all depends on the size of the network you are pretraining

**Comment by cuixianheng** [comment]
> @cuixianheng it all depends on the size of the network you are pretraining

I use the ResNet-50 as the encoder

**Comment by lucidrains** [comment]
@cuixianheng you could try using mixed precision https://pytorch-lightning.readthedocs.io/en/0.4.9/Trainer/Distributed%20training/#16-bit-mixed-precision
