### ISSUE TITLE
BYOL uses different augmentations for view1 and view2

### ISSUE THREAD

**Issue by OlivierDehaene** [lucidrains/byol-pytorch#31]
In your implementation, you use the same data augmentation pipeline for both views ([https://github.com/lucidrains/byol-pytorch/blob/master/byol_pytorch/byol_pytorch.py#L153](https://github.com/lucidrains/byol-pytorch/blob/master/byol_pytorch/byol_pytorch.py#L153)) like it was done in SimCLR and MoCo.

In the paper, they use different augmentations for the two views: 
![image](https://user-images.githubusercontent.com/23298448/95756156-b2924680-0ca5-11eb-8db7-e53782adfadd.png)

Is this voluntary?

Love your work btw, the implementations are always very clean :)

**Comment by lucidrains** [comment]
Thanks Olivier :) so it is applied twice, here https://github.com/lucidrains/byol-pytorch/blob/master/byol_pytorch/byol_pytorch.py#L187

**Comment by lucidrains** [comment]
@OlivierDehaene ohh no, I totally missed that! I can assure you though, from testimonies of others, that it still works well without this detail. It seems like the difference is mainly the gaussian blur probability, I'll have to reread it tonight to see why that is

**Comment by lucidrains** [comment]
@OlivierDehaene I've updated it so you can pass in a separate augmentation function, with the `augment_fn2` keyword https://github.com/lucidrains/byol-pytorch/tree/0.3.0#advanced

**Comment by OlivierDehaene** [comment]
@lucidrains Yes, I also missed this in my own implementation that's why I spotted it aha. In my case, without this pipeline, BYOL performed marginally worse than MoCo V2 and marginally better with it. A bit disingenuous that the paper does not compare results using the same DA pipeline... An ablation study would have been nice =P

**Comment by lucidrains** [comment]
@OlivierDehaene thanks for bringing it to my attention :)

**Comment by utkutpcgl** [comment]
Thanks to all, also note that brightness-contrast-saturation-hue values are different in original BYOL in table above compared to here: https://github.com/lucidrains/byol-pytorch/blob/6717204748c2a4f4f44b991d4c59ce5b99995582/byol_pytorch/byol_pytorch.py#L190
