### ISSUE TITLE
Error when training my own 1D dataset

### ISSUE THREAD

**Issue by QueeneTam** [lucidrains/byol-pytorch#34]
Thanks for your great work! Now I encounter a tricky problem:
Size of input x is [1024, 12, 7500], but after running 'image_one, image_two = self.augment1(x), self.augment2(x)' in line 195 of  byol_pytorch, size of image_one and image_two become [12, 7500]. 
I have checked my augment_fn and make sure them right. 
This problem sometimes happens in the initial beginning and sometimes happens in training loop.  
Can you give me some advices? Thanks a lot!

**Comment by lucidrains** [comment]
@QueeneTam this doesn't work for 1d datasets unfortunately, it only works for images!
