### ISSUE TITLE
Can't load ckpt

### ISSUE THREAD

**Issue by AndrewTal** [lucidrains/byol-pytorch#38]
I use byol-pytorch-master/examples/lightning/train.py to generate ckpt locally after training, but when I load ckpt, there will be the following errors. How should I load it? Thanks a lot!
<img width="818" alt="截屏2020-11-18 上午12 51 48" src="https://user-images.githubusercontent.com/49064155/99420664-730be980-2938-11eb-8d09-e6034047c209.png">

**Comment by AndrewTal** [comment]
I tried this and it seemed okay, I don't know if it is correct.
<img width="779" alt="截屏2020-11-18 下午12 19 15" src="https://user-images.githubusercontent.com/49064155/99483016-4e475e80-2998-11eb-95c4-0caeed45d704.png">


At the same time, the resnet parameters have also changed. Is the ResNet model saved in this way correct?

**Comment by aiyolo** [comment]
yes, ckpt['state_dict'] saves the model's parameters. The way that pytorch lightning load checkpoint is different from pytorch, you should try the following code instead:
```
from torchvision import models
resnet = models.resnet50(pretrained=False)
cfg = dict(
    net=resnet,
    image_size = 256,
    hidden_layer = 'avgpool',
    projection_size = 256,
    projection_hidden_size = 4096,
    moving_average_decay = 0.99
)
model = SelfSupervisedLearner.load_from_checkpoint(
            'lightning_logs/version_1/checkpoints/epoch=127.ckpt', **cfg
          )
```

**Comment by wencc-ucas** [comment]
model = SelfSupervisedLearner.load_from_checkpoint(
            'lightning_logs/version_1/checkpoints/epoch=127.ckpt', **cfg
          )

when I tried this, I got another issue:" TypeError: load_from_checkpoint() got an unexpected keyword argument 'net'"
