### ISSUE TITLE
Feat: Add image dataset normalization

### ISSUE THREAD

**Issue by YoniSchirris** [lucidrains/byol-pytorch#4]
Appendix B, page 13, bottom: 

_In both training and evaluation, we normalize color channelsby subtracting the average color and dividing by the standar deviation, computed on ImageNet, after applying the augmentations_

**Comment by lucidrains** [comment]
Ok, done! https://github.com/lucidrains/byol-pytorch/commit/ac84dff714b0b28f1ad6450f1e163e557cd7adda

**Comment by YoniSchirris** [comment]
Hi @lucidrains , could you make the normalization parameters a class parameter? I'll be using it on a different dataset. Would be nice to be able to just pip-install instead of forking and adjusting
