### ISSUE TITLE
AssertionError: hidden layer never emitted an output with multi-gpu training

### ISSUE THREAD

**Issue by reactivetype** [lucidrains/byol-pytorch#9]
I tried your library with a WideResnet40-2 model and used layer_index=-2.

The lightning example works fine for single-gpu but i got the error with multiple GPUs.

**Comment by lucidrains** [comment]
@reactivetype Hi Rindra! It works on my two GPUs for some reason, but I introduced a change here https://github.com/lucidrains/byol-pytorch/commit/fa1e338f82899cf14981292bffdb41197fbe8ecd to see if I could make a stab at the problem without being able to reproduce it. Could you let me know if that helped?

**Comment by lucidrains** [comment]
@reactivetype is this multiple GPUs on one machine or distributed?

**Comment by reactivetype** [comment]
@lucidrains  on one machine. I used 'dp' mode in lightning. i upgrade to 0.1.4 but still get the issue

**Comment by lucidrains** [comment]
@reactivetype that's weird, are you just running the script I supplied in the examples?

**Comment by lucidrains** [comment]
<img width="704" alt="Screen Shot 2020-06-27 at 8 27 53 PM" src="https://user-images.githubusercontent.com/108653/85937045-b47df880-b8b4-11ea-8d87-0a0d9b7c0677.png">
can you try using ddp?

**Comment by ranliu98** [comment]
Hi @lucidrains ,
thanks for the really nice implementation. I got the same issue using 2 GPUs with "dp".
